/*
  Warnings:

  - You are about to drop the column `grossSalary` on the `PayrollRunEmployee` table. All the data in the column will be lost.
  - You are about to drop the column `netSalary` on the `PayrollRunEmployee` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "PayrollRunEmployee" DROP COLUMN "grossSalary",
DROP COLUMN "netSalary",
ADD COLUMN     "afpConfiaDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "afpCrecerDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "afpStatus" TEXT,
ADD COLUMN     "bankLoansDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "baseSalary" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "bonuses" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "commissions" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "correlativo" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "earnedSalary" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "extraHolidayAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "extraHolidayHoursCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "extraPlanHoursAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "extraPlanHoursCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "fsvDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "holidayDaysAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "holidayDaysCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "hospitalDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "incomeTax" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "ipsfaDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isssHealthDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isssLeaveDeductionAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isssLeaveDeductionCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isssLeaveFullPayAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isssLeaveFullPayCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "isssStatus" TEXT,
ADD COLUMN     "judicialSeizure" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "lateArrivalsDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "netPay" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "nightHolidayAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "nightHolidayHoursCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "nightShiftAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "nightShiftHoursCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "otherDeductions" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "overtimeDayAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "overtimeDayHoursCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "overtimeNightAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "overtimeNightHoursCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "planHours" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "procuraduriaDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "regencies" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "reimbursements" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "restDaysWorkedAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "restDaysWorkedCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "secondPositions" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "stipends" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "taxableIncome" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "totalBenefits" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "totalDeductions" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "totalHolidaysAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unjustifiedAbsencesAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unjustifiedAbsencesCount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "unpaidLeaveDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vacationBonus" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vacationDaysAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vacationDaysTaken" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "vialidadDeduction" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "workedDays" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN     "workedHours" DECIMAL(18,2) NOT NULL DEFAULT 0;
